### ISSUE TITLE
ERROR:dts:I cannot read the commands repo: ~/.dt-shell/commands

### ISSUE THREAD

**Issue by MuyanXiao** [duckietown/docs-opmanual_duckiebot#78] opened 2018-10-14 18:51 UTC
I tried to update the shell and burn the sd card again, and got this error. And I couldn't go through the following steps.

**Comment by AndreaCensi** [comment] 2018-10-17 09:18
Did you try again with the newest shell?

If not, please post more accurate error.

**Comment by AleksandarPetrov** [comment] 2018-10-22 19:07
@MuyanXiao, if the problem is fixed, please close the issue

**Comment by MuyanXiao** [comment] 2018-11-04 15:16
I got new error, that I couldn't update the commands. No matter I do "dts update" or "dts commands update", it always gives "ERROR:dts:Duckietown Shell commands version 1.1.0". I tried removing the commands/ directory, or delete the whole "~/.dt-shell" to reconfigure, I still got this error. And then I don't have some commands any more, such as calibration.

**Comment by MuyanXiao** [comment] 2018-11-04 15:54
![screenshot from 2018-11-04 16-53-57](https://user-images.githubusercontent.com/32569292/47966412-4dae2a80-e052-11e8-8971-e7ba2b44f52b.png)

**Comment by liampaull** [comment] 2018-11-04 18:30
I get the same output

**Comment by liampaull** [comment] 2018-11-04 18:48
I'm going to close this for now and open an issue in the shell-commands repo

**Closed by liampaull** 2018-11-04 18:48 UTC

**Comment by AndreaCensi** [comment] 2018-11-06 15:07
@MuyanXiao the command is `dts update` not `dts commands update`.

**Comment by MuyanXiao** [comment] 2018-11-06 15:39
I got the same error using `dts update`

**Comment by liampaull** [comment] 2018-11-06 17:34
See here https://github.com/duckietown/duckietown-shell-commands/issues/66

**Comment by AndreaCensi** [comment] 2018-11-06 21:10
@breandan https://github.com/duckietown/duckietown-shell-commands/blame/c84aa18869187992eb8ba6731d7297c8792a1f28/update/__init__.py#L19
